title: Doctrine Database
description:  List of doctrines
remote_theme: tuur29/pages-themes-cayman
darkmode: true
color:
  header: "#000"
  gradient_left: "#57D45F"
  gradient_right: "#57D45E"
logo_url: 
gems:
- jekyll-seo-tag
